/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycongviec;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author STD_DELL
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DefaultTableModel tableModel;
    private DefaultTableModel tableEdit;
    private LoginJFrame parentFrame;
    private ListUsers listUsers;
    private User user;
    private int indexPlan,indexUser;
    
    public MainJFrame(java.awt.Frame parent, User user ,int i) {
        initComponents();
        this.setLocationRelativeTo(null);
        parentFrame = (LoginJFrame) parent;
        this.listUsers = parentFrame.listUsers;
        this.user = listUsers.getListUsers().get(i);
        if(!user.isCheckAdmin()) jButtonEditUsers.setVisible(false);
        jLabelUserName.setText("Tài khoản: " + user.getUser());        
        jLabelFullName.setText("Tên người dùng: " + user.getFullName());
        tableModel = (DefaultTableModel) jTableListPlans.getModel();
        List<Plan> listPlans = new ArrayList<>();
        listPlans = user.getListPlans();
        if(!(listPlans.isEmpty())){
            for(Plan plan: listPlans){
                tableModel.addRow(new Object[]{plan.getPlan(),plan.getPlace(),
                        plan.getBeginDate(),plan.getEndDate(),plan.getFinish()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddPlan = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFPlace = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jTFPlan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBHourBegin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCBMinuteBegin = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCBDayBegin = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCBMonthBegin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jCBYearBegin = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCBHourEnd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jCBMinuteEnd = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCBDayEnd = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCBMonthEnd = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jCBYearEnd = new javax.swing.JComboBox<>();
        jRBWeek = new javax.swing.JRadioButton();
        jRBMonth = new javax.swing.JRadioButton();
        jRBDay = new javax.swing.JRadioButton();
        jRBYear = new javax.swing.JRadioButton();
        jTFRepeatTimes = new javax.swing.JTextField();
        jLabelRepeatTimes = new javax.swing.JLabel();
        jRBNoRepeat = new javax.swing.JRadioButton();
        jDialogEditPlan = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTFPlace1 = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jButtonCancel1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jTFPlan1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCBHourBegin1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jCBMinuteBegin1 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCBDayBegin1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jCBMonthBegin1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jCBYearBegin1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCBHourEnd1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jCBMinuteEnd1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCBDayEnd1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jCBMonthEnd1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jCBYearEnd1 = new javax.swing.JComboBox<>();
        jFrameEditUsers = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEditUsers = new javax.swing.JTable();
        jButtonAddUser = new javax.swing.JButton();
        jButtonEditUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jDialogAddUser = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTFPassword = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTFFullName = new javax.swing.JTextField();
        jDBAddUser = new javax.swing.JButton();
        jDBCancel = new javax.swing.JButton();
        jDialogEditUser = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTFUser1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTFPassword1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTFFullName1 = new javax.swing.JTextField();
        jDBEditUser = new javax.swing.JButton();
        jDBCancel1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelUserName = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jButtonEditUsers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListPlans = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonAddPlan = new javax.swing.JButton();
        jButtonEditPlan = new javax.swing.JButton();
        jButtonDeletePlan = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();

        jDialogAddPlan.setTitle("Nhập thông tin");
        jDialogAddPlan.setSize(new java.awt.Dimension(450, 600));

        jLabel1.setText("Thêm công việc");

        jLabel2.setText("Tên công việc");

        jLabel3.setText("Địa điểm");

        jButtonAdd.setText("Thêm");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Bỏ qua");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Ngày bắt đầu");

        jLabel9.setText("Thời điểm");

        jCBHourBegin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel5.setText("giờ");

        jCBMinuteBegin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel16.setText("phút");

        jLabel6.setText("Ngày");

        jCBDayBegin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel7.setText("Tháng");

        jCBMonthBegin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel8.setText("Năm");

        jCBYearBegin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBDayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBMonthBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jCBHourBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBMinuteBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jCBHourBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCBMinuteBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBMonthBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCBYearBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Ngày kết thúc");
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 13));

        jLabel14.setText("Thời điểm");

        jCBHourEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel15.setText("giờ");

        jCBMinuteEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel17.setText("phút");

        jLabel10.setText("Ngày");

        jCBDayEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel11.setText("Tháng");

        jCBMonthEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel12.setText("Năm");

        jCBYearEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jCBHourEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBMinuteEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCBMonthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jCBMinuteEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jCBHourEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jCBMonthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jCBYearEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRBWeek);
        jRBWeek.setText("Hằng tuần");
        jRBWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBWeekActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBMonth);
        jRBMonth.setText("Hằng tháng");
        jRBMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMonthActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBDay);
        jRBDay.setText("Hằng ngày");
        jRBDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBDayActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBYear);
        jRBYear.setText("Hàng năm");
        jRBYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBYearActionPerformed(evt);
            }
        });

        jLabelRepeatTimes.setText("Số lần lặp");

        buttonGroup1.add(jRBNoRepeat);
        jRBNoRepeat.setText("Không lặp lại");
        jRBNoRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoRepeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddPlanLayout = new javax.swing.GroupLayout(jDialogAddPlan.getContentPane());
        jDialogAddPlan.getContentPane().setLayout(jDialogAddPlanLayout);
        jDialogAddPlanLayout.setHorizontalGroup(
            jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                        .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPlan)
                                    .addComponent(jTFPlace)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddPlanLayout.createSequentialGroup()
                        .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBNoRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRBWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRBMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jRBYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFRepeatTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddPlanLayout.createSequentialGroup()
                        .addComponent(jRBDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114)
                        .addComponent(jLabelRepeatTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
            .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButtonAdd)
                        .addGap(111, 111, 111)
                        .addComponent(jButtonCancel))
                    .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogAddPlanLayout.setVerticalGroup(
            jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogAddPlanLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBNoRepeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBDay)
                    .addComponent(jLabelRepeatTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBWeek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBMonth)
                    .addComponent(jTFRepeatTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAdd))
                .addContainerGap())
        );

        jDialogEditPlan.setTitle("Nhập thông tin");
        jDialogEditPlan.setSize(new java.awt.Dimension(450, 450));

        jLabel18.setText("Sửa công việc");

        jLabel19.setText("Tên công việc");

        jLabel20.setText("Địa điểm");

        jButtonEdit.setText("Sửa");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonCancel1.setText("Bỏ qua");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("Ngày bắt đầu");

        jLabel25.setText("Thời điểm");

        jCBHourBegin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel31.setText("giờ");

        jCBMinuteBegin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel33.setText("phút");

        jLabel22.setText("Ngày");

        jCBDayBegin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel23.setText("Tháng");

        jCBMonthBegin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel24.setText("Năm");

        jCBYearBegin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBDayBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBMonthBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(36, 36, 36)
                        .addComponent(jCBHourBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCBMinuteBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBYearBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBHourBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jCBMinuteBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDayBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBMonthBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jCBYearBegin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setText("Ngày kết thúc");

        jLabel30.setText("Thời điểm");

        jCBHourEnd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        jLabel32.setText("giờ");

        jCBMinuteEnd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel34.setText("phút");

        jLabel26.setText("Ngày");

        jCBDayEnd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel27.setText("Tháng");

        jCBMonthEnd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel28.setText("Năm");

        jCBYearEnd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBDayEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBMonthEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBYearEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addGap(33, 33, 33)
                        .addComponent(jCBHourEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBMinuteEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBHourEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jCBMinuteEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBDayEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jCBMonthEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jCBYearEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEditPlanLayout = new javax.swing.GroupLayout(jDialogEditPlan.getContentPane());
        jDialogEditPlan.getContentPane().setLayout(jDialogEditPlanLayout);
        jDialogEditPlanLayout.setHorizontalGroup(
            jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEditPlanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEditPlanLayout.createSequentialGroup()
                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogEditPlanLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel1)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogEditPlanLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogEditPlanLayout.createSequentialGroup()
                                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFPlan1)
                                    .addComponent(jTFPlace1))
                                .addGap(55, 55, 55))
                            .addGroup(jDialogEditPlanLayout.createSequentialGroup()
                                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 80, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        jDialogEditPlanLayout.setVerticalGroup(
            jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditPlanLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPlan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogEditPlanLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel1)
                    .addComponent(jButtonEdit))
                .addContainerGap())
        );

        jFrameEditUsers.setSize(new java.awt.Dimension(396, 327));

        jTableEditUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Tên người dùng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEditUsers);

        jButtonAddUser.setText("Thêm");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonEditUser.setText("Sửa");
        jButtonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUserActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setText("Xóa");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameEditUsersLayout = new javax.swing.GroupLayout(jFrameEditUsers.getContentPane());
        jFrameEditUsers.getContentPane().setLayout(jFrameEditUsersLayout);
        jFrameEditUsersLayout.setHorizontalGroup(
            jFrameEditUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jFrameEditUsersLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonAddUser)
                .addGap(66, 66, 66)
                .addComponent(jButtonEditUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonDeleteUser)
                .addGap(40, 40, 40))
        );
        jFrameEditUsersLayout.setVerticalGroup(
            jFrameEditUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameEditUsersLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jFrameEditUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddUser)
                    .addComponent(jButtonEditUser)
                    .addComponent(jButtonDeleteUser))
                .addGap(15, 15, 15))
        );

        jDialogAddUser.setSize(new java.awt.Dimension(350, 300));

        jLabel35.setText("Thêm tài khoản");

        jLabel36.setText("Tài khoản");

        jLabel37.setText("Mật khẩu");

        jLabel38.setText("Tên người dùng");

        jDBAddUser.setText("Thêm");
        jDBAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBAddUserActionPerformed(evt);
            }
        });

        jDBCancel.setText("Bỏ qua");
        jDBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddUserLayout = new javax.swing.GroupLayout(jDialogAddUser.getContentPane());
        jDialogAddUser.getContentPane().setLayout(jDialogAddUserLayout);
        jDialogAddUserLayout.setHorizontalGroup(
            jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddUserLayout.createSequentialGroup()
                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAddUserLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogAddUserLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogAddUserLayout.createSequentialGroup()
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogAddUserLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogAddUserLayout.createSequentialGroup()
                                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDBAddUser)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogAddUserLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jTFFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialogAddUserLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jDBCancel)))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jDialogAddUserLayout.setVerticalGroup(
            jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddUserLayout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFUser, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDialogAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBAddUser)
                    .addComponent(jDBCancel))
                .addGap(0, 122, Short.MAX_VALUE))
        );

        jDialogEditUser.setSize(new java.awt.Dimension(350, 300));

        jLabel39.setText("Sửa tài khoản");

        jLabel40.setText("Tài khoản");

        jLabel41.setText("Mật khẩu");

        jLabel42.setText("Tên người dùng");

        jDBEditUser.setText("Sửa");
        jDBEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBEditUserActionPerformed(evt);
            }
        });

        jDBCancel1.setText("Bỏ qua");
        jDBCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEditUserLayout = new javax.swing.GroupLayout(jDialogEditUser.getContentPane());
        jDialogEditUser.getContentPane().setLayout(jDialogEditUserLayout);
        jDialogEditUserLayout.setHorizontalGroup(
            jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jTFPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jTFUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDBEditUser)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jTFFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialogEditUserLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jDBCancel1)))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jDialogEditUserLayout.setVerticalGroup(
            jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditUserLayout.createSequentialGroup()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jDialogEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBEditUser)
                    .addComponent(jDBCancel1))
                .addGap(0, 122, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý công việc");

        jLabelUserName.setPreferredSize(new java.awt.Dimension(30, 13));

        jButtonEditUsers.setText("Edit Users");
        jButtonEditUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUsersActionPerformed(evt);
            }
        });

        jTableListPlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên công việc", "Địa điểm", "Ngày bắt đầu", "Ngày kết thúc", "Hoàn thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListPlans);

        jButtonAddPlan.setText("Thêm công việc");
        jButtonAddPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPlanActionPerformed(evt);
            }
        });

        jButtonEditPlan.setText("Sửa công việc");
        jButtonEditPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPlanActionPerformed(evt);
            }
        });

        jButtonDeletePlan.setText("Xóa công việc");
        jButtonDeletePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePlanActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonLogOut.setText("Log out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonAddPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditPlan)
                .addGap(145, 145, 145)
                .addComponent(jButtonDeletePlan)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEditUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddPlan)
                    .addComponent(jButtonEditPlan)
                    .addComponent(jButtonDeletePlan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void updateListPlan(){
        tableModel.setRowCount(0);
        List<Plan> listPlans = new ArrayList<>();
        listPlans = this.user.getListPlans();
        if(!listPlans.isEmpty()){
            for(Plan plan: listPlans){
                tableModel.addRow(new Object[]{plan.getPlan(),plan.getPlace(),
                        plan.getBeginDate(),plan.getEndDate(),plan.getFinish()});
            }
        }
        Main.save();
    }
    
    public void updateListUser(){
        tableEdit.setRowCount(0);
        List<User> listUsers= new ArrayList<>();
        listUsers = this.listUsers.getListUsers();
        if(!(listUsers.isEmpty())){
            for(User user: listUsers){
                tableEdit.addRow(new Object[]{user.getUser(),
                        user.getPassword(),user.getFullName()});
            }
        }
        Main.save();
    }
    
    public void addPlan(Plan planAdd){
        if(!user.addPlan(planAdd)){
            JOptionPane.showMessageDialog(null, "Trùng mốc thời gian với công việc khác");
        }
        updateListPlan();
    }
    
    public boolean addUser(User userAdd){
        if(!listUsers.addUser(userAdd)){
            JOptionPane.showMessageDialog(null, "Trùng tên tài khoản");
            return false;
        }
        updateListUser();
        return true;
    }
    
    private void jButtonAddPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPlanActionPerformed
        // TODO add your handling code here:
        jDialogAddPlan.setLocationRelativeTo(null);
        jDialogAddPlan.setVisible(true);
        jTFPlan.setText("");
        jTFPlace.setText("");
        jRBNoRepeat.setSelected(true);
        jLabelRepeatTimes.setVisible(false);
        jTFRepeatTimes.setVisible(false);
    }//GEN-LAST:event_jButtonAddPlanActionPerformed

    private void jButtonDeletePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePlanActionPerformed
        // TODO add your handling code here:
        indexPlan = jTableListPlans.getSelectedRow();
        if(user.getListPlans().size() == 0){
            JOptionPane.showMessageDialog(this, "Danh sách công việc trống !");
        } else if(indexPlan == -1){
            JOptionPane.showMessageDialog(this, "Chọn công việc !");
        } else{
            user.deletePlan(indexPlan);
            updateListPlan();
        }
    }//GEN-LAST:event_jButtonDeletePlanActionPerformed

    private void jButtonEditPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPlanActionPerformed
        // TODO add your handling code here:
        indexPlan = jTableListPlans.getSelectedRow();
        if(user.getListPlans().isEmpty()){
            JOptionPane.showMessageDialog(this, "Danh sách công việc trống !");
        } else if(indexPlan == -1){
            JOptionPane.showMessageDialog(this, "Chọn công việc !");
        } else{
            Plan tmp = user.getListPlans().get(indexPlan);
            jTFPlan1.setText(tmp.getPlan());
            jTFPlace1.setText(tmp.getPlace());
            jCBHourBegin1.setSelectedIndex(tmp.getBeginDate().getHour());
            jCBMinuteBegin1.setSelectedIndex(tmp.getBeginDate().getMinute());
            jCBDayBegin1.setSelectedIndex(tmp.getBeginDate().getDayOfMonth()-1);
            jCBMonthBegin1.setSelectedIndex(tmp.getBeginDate().getMonthValue()-1);
            jCBYearBegin1.setSelectedIndex(tmp.getBeginDate().getYear()-2021);
            
            jCBHourEnd1.setSelectedIndex(tmp.getEndDate().getHour());
            jCBMinuteEnd1.setSelectedIndex(tmp.getEndDate().getMinute());
            jCBDayEnd1.setSelectedIndex(tmp.getEndDate().getDayOfMonth()-1);
            jCBMonthEnd1.setSelectedIndex(tmp.getEndDate().getMonthValue()-1);
            jCBYearEnd1.setSelectedIndex(tmp.getEndDate().getYear()-2021);

            jDialogEditPlan.setLocationRelativeTo(null);
            jDialogEditPlan.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditPlanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        
        int hourBegin = jCBHourBegin1.getSelectedIndex();
        int minuteBegin = jCBMinuteBegin1.getSelectedIndex();
        int dayBegin = jCBDayBegin1.getSelectedIndex() + 1;
        int monthBegin = jCBMonthBegin1.getSelectedIndex() + 1;
        int yearBegin = Integer.parseInt(jCBYearBegin1.getSelectedItem().toString());
        
        int hourEnd = jCBHourEnd1.getSelectedIndex();
        int minuteEnd = jCBMinuteEnd1.getSelectedIndex();
        int dayEnd = jCBDayEnd1.getSelectedIndex() + 1;
        int monthEnd = jCBMonthEnd1.getSelectedIndex() + 1;
        int yearEnd = Integer.parseInt(jCBYearEnd1.getSelectedItem().toString());
        
        LocalDateTime beginDT = null,endDT = null;
        boolean isOK = true;
        
        try{
            beginDT = LocalDateTime.of(yearBegin,monthBegin,
                    dayBegin,hourBegin,minuteBegin);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Định dạng sai !");
            isOK = false;
        }
        
        try{
             endDT = LocalDateTime.of(yearEnd,monthEnd,
                    dayEnd,hourEnd,minuteEnd);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Định dạng sai !");
            isOK = false;
        }
        if(!beginDT.isBefore(endDT)){
            JOptionPane.showMessageDialog(null, "Ngược thời gian");
            isOK = false;
        }

        if(jTFPlan1.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin !");
            isOK = false;
        }

        if(isOK){
            Plan plan = new Plan(jTFPlan1.getText(), beginDT, endDT,
                    jTFPlace1.getText(),false);
            user.deletePlan(indexPlan);
            this.addPlan(plan);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < jTableListPlans.getRowCount(); i++){
            user.getListPlans().get(i).setFinish((Boolean) tableModel.getValueAt(i, 4));
            Main.save();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonEditUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUsersActionPerformed
        // TODO add your handling code here:
        jFrameEditUsers.setLocationRelativeTo(null);
        tableEdit = (DefaultTableModel) jTableEditUsers.getModel();
        tableEdit.setRowCount(0);
        List<User> listUsers= new ArrayList<>();
        listUsers = this.listUsers.getListUsers();
        if(!(listUsers.isEmpty())){
            for(User user: listUsers){
                tableEdit.addRow(new Object[]{user.getUser(),
                        user.getPassword(),user.getFullName()});
            }
        }
        jFrameEditUsers.setVisible(true);
    }//GEN-LAST:event_jButtonEditUsersActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        jDialogAddUser.setLocationRelativeTo(null);
        jDialogAddUser.setVisible(true);
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
        jDialogEditPlan.dispose();
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    private void jDBAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBAddUserActionPerformed
        // TODO add your handling code here:
        List<Plan> list = new ArrayList<>();
        User user = new User(jTFUser.getText(),jTFPassword.getText(),
                jTFFullName.getText(),list,false); 
        this.addUser(user);
    }//GEN-LAST:event_jDBAddUserActionPerformed

    private void jDBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBCancelActionPerformed
        // TODO add your handling code here:
        jDialogAddUser.dispose();
    }//GEN-LAST:event_jDBCancelActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        // TODO add your handling code here:
        indexUser = jTableEditUsers.getSelectedRow();
        if(listUsers.getListUsers().size() == 0){
            JOptionPane.showMessageDialog(this, "Danh sách tài khoản trống !");
        } else if(indexUser == -1){
            JOptionPane.showMessageDialog(this, "Chọn tài khoản !");
        } else{
            listUsers.deleteUser(indexUser);
            updateListUser();
        }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jDBEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBEditUserActionPerformed
        // TODO add your handling code here:
        User tmp = listUsers.getListUsers().get(indexUser);
        User user = new User(jTFUser1.getText(),jTFPassword1.getText(),
                jTFFullName1.getText(),tmp.getListPlans(),tmp.isCheckAdmin());
        listUsers.deleteUser(indexUser);
        if(!addUser(user)){
            addUser(tmp);
        }
    }//GEN-LAST:event_jDBEditUserActionPerformed

    private void jDBCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBCancel1ActionPerformed
        // TODO add your handling code here:
        jDialogEditUser.dispose();
    }//GEN-LAST:event_jDBCancel1ActionPerformed

    private void jButtonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUserActionPerformed
        // TODO add your handling code here:
        indexUser = jTableEditUsers.getSelectedRow();
        if(listUsers.getListUsers().size() == 0){
            JOptionPane.showMessageDialog(this, "Danh sách tài khoản trống !");
        } else if(indexUser == -1){
            JOptionPane.showMessageDialog(this, "Chọn tài khoản !");
        } else{
            User tmp = listUsers.getListUsers().get(indexUser);
            jTFUser1.setText(tmp.getUser());
            jTFPassword1.setText(tmp.getPassword());
            jTFFullName1.setText(tmp.getFullName());
            jDialogEditUser.setLocationRelativeTo(null);
            jDialogEditUser.setVisible(true);
        }  
    }//GEN-LAST:event_jButtonEditUserActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginJFrame newLoginJFrame = new LoginJFrame(listUsers);
        newLoginJFrame.setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.jDialogAddPlan.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        int hourBegin = jCBHourBegin.getSelectedIndex();
        int minuteBegin = jCBMinuteBegin.getSelectedIndex();
        int dayBegin = jCBDayBegin.getSelectedIndex() + 1;
        int monthBegin = jCBMonthBegin.getSelectedIndex() + 1;
        int yearBegin = Integer.parseInt(jCBYearBegin.getSelectedItem().toString());

        int hourEnd = jCBHourEnd.getSelectedIndex();
        int minuteEnd = jCBMinuteEnd.getSelectedIndex();
        int dayEnd = jCBDayEnd.getSelectedIndex() + 1;
        int monthEnd = jCBMonthEnd.getSelectedIndex() + 1;
        int yearEnd = Integer.parseInt(jCBYearEnd.getSelectedItem().toString());

        LocalDateTime beginDT = null;
        LocalDateTime endDT = null;
        boolean isOK = true;
        int repeatTimes = 1;

        if(jTFPlan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng điền đủ thông tin !");
            isOK = false;
        }

        try{
            beginDT = LocalDateTime.of(yearBegin,monthBegin,
                dayBegin,hourBegin,minuteBegin);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Định dạng sai !");
            isOK = false;
        }

        try{
            endDT = LocalDateTime.of(yearEnd,monthEnd,
                dayEnd,hourEnd,minuteEnd);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Định dạng sai !");
            isOK = false;
        }
        
        if(!beginDT.isBefore(endDT)){
            JOptionPane.showMessageDialog(null, "Ngược thời gian !");
            isOK = false;
        }
        
        try {
            if(!jRBNoRepeat.isSelected()){
                repeatTimes = Integer.parseInt(jTFRepeatTimes.getText());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Sai định dạng số lần lặp");
            isOK = false;
        }
        
        if(isOK){
            String planName = jTFPlan.getText();
            String place = jTFPlace.getText();
            if(jRBNoRepeat.isSelected()){
                Plan plan = new Plan(planName, beginDT, endDT, place,false);
                this.addPlan(plan);
                return;
            }
            if(jRBDay.isSelected()){
                for(int i = 0; i < repeatTimes; i++){
                    Plan plan = new Plan(planName, beginDT.plusDays(i), 
                            endDT.plusDays(i), place,false);
                    this.addPlan(plan);
                }
                return;
            }
            if(jRBWeek.isSelected()){
                for(int i = 0; i < repeatTimes; i++){
                    Plan plan = new Plan(planName, beginDT.plusWeeks(i), 
                            endDT.plusWeeks(i), place,false);
                    this.addPlan(plan);
                }
                return;
            }
            if(jRBMonth.isSelected()){
                for(int i = 0; i < repeatTimes; i++){
                    Plan plan = new Plan(planName, beginDT.plusMonths(i), 
                            endDT.plusMonths(i), place,false);
                    this.addPlan(plan);
                }
                return;
            }
            if(jRBYear.isSelected()){
                for(int i = 0; i < repeatTimes; i++){
                    Plan plan = new Plan(planName, beginDT.plusYears(i), 
                            endDT.plusYears(i), place,false);
                    this.addPlan(plan);
                }
            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jRBDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBDayActionPerformed
        // TODO add your handling code here:
        jLabelRepeatTimes.setVisible(true);
        jTFRepeatTimes.setVisible(true);
    }//GEN-LAST:event_jRBDayActionPerformed

    private void jRBNoRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoRepeatActionPerformed
        // TODO add your handling code here:
        jLabelRepeatTimes.setVisible(false);
        jTFRepeatTimes.setVisible(false);
    }//GEN-LAST:event_jRBNoRepeatActionPerformed

    private void jRBWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBWeekActionPerformed
        // TODO add your handling code here:
        jLabelRepeatTimes.setVisible(true);
        jTFRepeatTimes.setVisible(true);
    }//GEN-LAST:event_jRBWeekActionPerformed

    private void jRBMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMonthActionPerformed
        // TODO add your handling code here:
        jLabelRepeatTimes.setVisible(true);
        jTFRepeatTimes.setVisible(true);
    }//GEN-LAST:event_jRBMonthActionPerformed

    private void jRBYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBYearActionPerformed
        // TODO add your handling code here:
        jLabelRepeatTimes.setVisible(true);
        jTFRepeatTimes.setVisible(true);
    }//GEN-LAST:event_jRBYearActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddPlan;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonDeletePlan;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEditPlan;
    private javax.swing.JButton jButtonEditUser;
    private javax.swing.JButton jButtonEditUsers;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jCBDayBegin;
    private javax.swing.JComboBox<String> jCBDayBegin1;
    private javax.swing.JComboBox<String> jCBDayEnd;
    private javax.swing.JComboBox<String> jCBDayEnd1;
    private javax.swing.JComboBox<String> jCBHourBegin;
    private javax.swing.JComboBox<String> jCBHourBegin1;
    private javax.swing.JComboBox<String> jCBHourEnd;
    private javax.swing.JComboBox<String> jCBHourEnd1;
    private javax.swing.JComboBox<String> jCBMinuteBegin;
    private javax.swing.JComboBox<String> jCBMinuteBegin1;
    private javax.swing.JComboBox<String> jCBMinuteEnd;
    private javax.swing.JComboBox<String> jCBMinuteEnd1;
    private javax.swing.JComboBox<String> jCBMonthBegin;
    private javax.swing.JComboBox<String> jCBMonthBegin1;
    private javax.swing.JComboBox<String> jCBMonthEnd;
    private javax.swing.JComboBox<String> jCBMonthEnd1;
    private javax.swing.JComboBox<String> jCBYearBegin;
    private javax.swing.JComboBox<String> jCBYearBegin1;
    private javax.swing.JComboBox<String> jCBYearEnd;
    private javax.swing.JComboBox<String> jCBYearEnd1;
    private javax.swing.JButton jDBAddUser;
    private javax.swing.JButton jDBCancel;
    private javax.swing.JButton jDBCancel1;
    private javax.swing.JButton jDBEditUser;
    private javax.swing.JDialog jDialogAddPlan;
    private javax.swing.JDialog jDialogAddUser;
    private javax.swing.JDialog jDialogEditPlan;
    private javax.swing.JDialog jDialogEditUser;
    private javax.swing.JFrame jFrameEditUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelRepeatTimes;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRBDay;
    private javax.swing.JRadioButton jRBMonth;
    private javax.swing.JRadioButton jRBNoRepeat;
    private javax.swing.JRadioButton jRBWeek;
    private javax.swing.JRadioButton jRBYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTFFullName;
    private javax.swing.JTextField jTFFullName1;
    private javax.swing.JTextField jTFPassword;
    private javax.swing.JTextField jTFPassword1;
    private javax.swing.JTextField jTFPlace;
    private javax.swing.JTextField jTFPlace1;
    private javax.swing.JTextField jTFPlan;
    private javax.swing.JTextField jTFPlan1;
    private javax.swing.JTextField jTFRepeatTimes;
    private javax.swing.JTextField jTFUser;
    private javax.swing.JTextField jTFUser1;
    private javax.swing.JTable jTableEditUsers;
    private javax.swing.JTable jTableListPlans;
    // End of variables declaration//GEN-END:variables
}
